package com.ex.day2;

public class UnderstandingException {

	public static void main(String[] args) {

		int[] arr = new int[4];
		
		try {
			arr[0] = 1;
			arr[4] = 5;
			
			System.out.println(arr[4]);
		} catch (ArrayIndexOutOfBoundsException e) {
			System.out.println("Index out of bounds exception caught");
			System.out.println(e.getMessage());
			e.printStackTrace();
		}
		
		System.out.println("asdf");
	}

}
