package com.revature.exceptions;

public class UnderstandingExceptions {
	public static void main(String[] args) {
		int arr[] = new int[4];
		arr[0] = 1;
		try {
			arr[4] = 50;
		} catch (ArrayIndexOutOfBoundsException e) {
			System.out.println("Potato");
		}
	}
}
