package com.ex.day2;

public class UnderstandingExecptions {

	public static void main(String[] args) {
		try{
//		int[] arr = new int[4];
//		arr[0] = 1;
//		arr[4] = 5;
//		System.out.println(arr[4]);
		String str = null;
		System.out.println(str.indexOf('a'));
		}
//		catch(Exception e){
//			e.printStackTrace();
//		}
		catch(NullPointerException e){
			System.out.println("inside catch block");
			System.out.println(e.getMessage());
			e.printStackTrace();
		
		}
		finally{
			System.out.println("inside finally block");
		}
		System.out.println("hey i passed the exection");
	}

}
